name: main
on:
  workflow_call:
    inputs:
      process_env:
        required: true
	type: string
jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: check-secret
        shell: bash
        run: echo "process_env: ${{ inputs.process_env }}"
