name: Release
on:
  release:
    types: [published]
jobs:
  checkout-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  run-main:
    uses: ./.github/workflows/main.yml
    with:
      process_env: test
