name: Run some common jobs
on:
  workflow_call:
    inputs:
      versions:
        required: true
        type: string
jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.versions }}
  proceed-if-a:
    if: ${{ contains(vars.versions, '2') == true }}
    uses: ivansa-ru/action-tests/.github/workflows/run-a.yml@master
  proceed-if-b:
    if: contains(vars.versions, '3') == true
    uses: ivansa-ru/action-tests/.github/workflows/run-b.yml@master
