name: Run some common jobs
on:
  workflow_call:
    inputs:
      versions:
        required: true
        type: string
jobs:
  proceed-if-a:
    if: contains(env.versions, '2') == true
    uses: ivansa-ru/action-tests/.github/workflows/run-a.yml
  proceed-if-b:
    if: contains(env.versions, '3') == true
    uses: ivansa-ru/action-tests/.github/workflows/run-b.yml
