name: Test ml
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: |
      if test -f required-binaries.txt; then
        cat required-binaries.txt
      else
        echo "no required binaries"
      fi

