name: Test ml
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: |
        if test -f required-binaries.txt; then
          sudo apt-get update && sudo apt-get -y install $(cat required-binaries.txt)
        else
          echo "no required binaries"
        fi

